apps/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)
from .views import register, profile, login_register

app_name = "users"

urlpatterns = [
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('login_register/', login_register, name='login-register'),
    path(
        '',
        LoginView.as_view(
            template_name='users/login.html',
            redirect_authenticated_user=True
        ),
        name='login'
    ),
    path('logout/',
        LogoutView.as_view(template_name='users/logout.html'),
        name='logout'),
    path(
        'password-reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset.html',
            email_template_name='users/password_reset_email.html',
            success_url=reverse_lazy('users:password_reset_done')
        ),
        name='password_reset'
    ),
    path(
        'password-reset/done',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:login')
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    )
]

main/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.eventos.urls', namespace='eventos')),
    path('eventos/', include('apps.eventos.urls', namespace='apieventos')),
    path('locais/', include('apps.locais.urls', namespace='locais')),
    path('users/', include('apps.users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # media files

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from PIL import Image
from . import roles
from apps.locais.models import Local, Bimby

class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address.')
        if not username:
            raise ValueError('Users must have a username.')
        user = self.model(
            email=self.normalize_email(email),
            username=username
            )
        user.set_password(password)
        user.save()
        return user


    def create_superuser(self, email, username, password=None):
        user = self.create_user(
            email=email,
            username=username,
            password=password
        )
        user.role=roles.ADMIN
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class User(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True, verbose_name="E-mail")
    username = models.CharField(max_length=30, unique=True, verbose_name="Nome de Utilizador")
    first_name = models.CharField(max_length=80, blank=True, null=True, verbose_name="Nome")
    last_name = models.CharField(max_length=80, blank=True, null=True, verbose_name="Apelido")
    loja = models.ForeignKey(Local, null=True, on_delete=models.SET_NULL)
    bimby = models.ForeignKey(Bimby, null=True, on_delete=models.SET_NULL)
    aceito = models.BooleanField(default=False)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    role = models.PositiveSmallIntegerField(
        choices=roles.TYPES, default=roles.USER)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    
    USERNAME_FIELD = 'email' #instead of username
    # USERNAME_FIELD and password are required by default
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    def role_is_admin(self):
        return self.role == roles.ADMIN


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # first_name = models.CharField(max_length=80)
    # last_name = models.CharField(max_length=80)
    # loja = models.ForeignKey(Local, null=True, on_delete=models.SET_NULL)
    # bimby = models.ForeignKey(Bimby, null=True, on_delete=models.SET_NULL)
    # aceito = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.user.username} Profile'

apps/users/forms.py
from django import forms
from .models import User, Profile
from apps.locais.models import Local
from django.utils.safestring import mark_safe
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    aceito = forms.BooleanField(widget=forms.CheckboxInput(),
                           label=mark_safe('Aceito a <a class="x" href="https://www.vorwerk.com/pt/pt/c/home/geral/politica-de-privacidade" target="_blank">Política de Privacidade</a>'))

    class Meta:
        model = User
        fields = ['email', 'username', 'first_name', 'last_name', 'bimby', 'loja', 'aceito', 'role']
        help_texts = {
            'password1': '',
            'password2': ''
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].required = False
        self.fields['password2'].required = False
        self.fields['password1'].widget.attrs['hidden'] = True
        self.fields['password2'].widget.attrs['hidden'] = True
        self.fields['password1'].label = ''
        self.fields['password2'].label = ''
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''
        self.fields['email'].label = 'E-mail'
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['aceito'].required = True
        self.fields['loja'].queryset = Local.objects.all().order_by("nome")


class ProfileRegisterForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['user']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].required = False


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['email', 'username', 'first_name', 'last_name', 'bimby']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetCompleteView, PasswordResetDoneView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse

from .models import Profile, User
from .forms import UserRegisterForm, UserUpdateForm, ProfileRegisterForm
from .roles import role_required, ADMIN


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            reset_password_form = PasswordResetForm(data={'email': email})
            if reset_password_form.is_valid():
                reset_password_form.save(request=request,
                    email_template_name='users/password_define_email.txt',
                    html_email_template_name='users/password_define_email.html')
                messages.success(request,
                    f'Conta criada com sucesso. Consulte a caixa de correio {email} para definir a palavra-passe')
                return redirect('users:login')
            else:
                messages.error(request,
                    'Problemas com o envio de email para definir a password...')
            return redirect('users:login')
        else:
            messages.error(request,
                'Problemas com a criação de conta. Ver informação em baixo...')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        if u_form.is_valid():
            u_form.save()
            messages.success(request, 'A tua conta foi atualizada!')
            return redirect('users:profile')
        else:
            messages.error(request,
                'Problemas a atualizar a tua conta, vê os erros em baixo...')
    else:
        u_form = UserUpdateForm(instance=request.user)
    context = {
        'u_form': u_form,
    }
    return render(request, 'users/profile.html', context)


def login_register(request):
    return render(request, 'users/login_register.html')


class MyPasswordResetCompleteView(PasswordResetCompleteView):
    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        messages.success(request, 'A sua palavra-passe foi definida com sucesso \
            Faça o login agora.')
        return redirect('users:login')

class MyPasswordResetDoneView(PasswordResetDoneView):
    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        messages.success(request, 'Um e-mail acabou de ser enviado com as \
            instruções para redefinir a sua senha... Confirme, por favor.')
        return redirect('users:login')

apps/users/templates/users/login.html
{% extends "base_bg.html" %}
{% load crispy_forms_tags %}

{% block content%}
<div class="row mb-5">
    <div class="col-12 col-lg-8 offset-lg-2">
        <div class="heroimgbox-login p-4 mt-5">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4" style="color: #e87e19;">Iniciar Sessão</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Iniciar Sessão</button>
                </div>
            </form>
            <div class="pb-2">
                <p class="text-muted">
                    Ainda não se registou? <a href="{% url 'users:register' %}" style="color: #e87e19;">Registe-se aqui</a>
                </p>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Esqueceu-se da sua palavra-passe? <a href="{% url 'users:password_reset' %}" style="color: #e87e19;">Recupere aqui</a>
                </small>
            </div>
        </div>
    </div>
</div>
{% endblock content%}

apps/users/templates/users/login_register.html
{% extends "base_bg.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="row">
	<div class="col-12 col-md-8 offset-md-2">
		<div class="heroimgbox-login p-4 my-5">
            <h5 class="text-center">Ainda não se registou?</h5>
            <div class="text-center mb-4">
                <a class="btn" href="{% url 'users:register' %}">Registar</a>
            </div>
            <h5 class="text-center">Já está registado?</h5>
            <div class="text-center">
                <a class="btn" href="{% url 'users:login' %}">Login</a> <br>
            </div>
		</div>
	</div>
</div>
{% endblock %}

apps/users/templates/users/logout.html
{% extends "base.html" %}
{% block content %}
    <h2>Acabou de terminar sessão...</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'users:login' %}">Fazer Login outravez..</a>
        </small>
    </div>
{% endblock content%}

apps/users/templates/users/password_define_email.html
<!-- <p>
    Acabou de receber este mail, depois da sua conta ter sido criada com o endereço: {{ user.email }}...
    Para definir a senha, clique <a href="{{ protocol}}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">AQUI</a>.
</p>
<p>Se não sabe a razão de ter recebido este e-mail, ignore, por favor.</p> -->
<p>Olá,</p>
<p>Está a receber este e-mail porque criou uma conta com e-mail {{ user.email }} no site <a href="https://diaabertobimby.bimby.pt">diaabertobimby.bimby.pt</a>. Para definir a palavra-passe, <a href="{{ protocol}}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">clique aqui</a>.</p>
<p>Se não sabe a razão de ter recebido este e-mail, ignore, por favor.</p>
<p>Obrigada,<br>
Equipa Bimby®
</p>

apps/users/templates/users/password_reset.html
{% extends "base_bg.html" %}
{% load crispy_forms_tags %}

{% block content%}
<div class="row">
    <div class="col-12 col-lg-8 offset-lg-2">
        <div class="heroimgbox-login p-4 mt-5">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Recuperar Palavra-Passe</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Pedir Palavra-Passe</button>
                </div>
            </form>
        </div>
    </div> 
</div>
{% endblock content%}

apps/users/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block content%}
    <div class="alert alert-info">
        A sua palavra-passe foi definida.
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'users:login' %}">Inicie sessão aqui</a>
        </small>
    </div>
{% endblock content%}

apps/users/templates/users/password_reset_confirm.html
{% extends "base_bg.html" %}
{% load crispy_forms_tags %}

{% block content%}
<div class="row">
    <div class="col-12 col-lg-8 offset-lg-2">
        <div class="heroimgbox-login p-4 my-5">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Definir Palavra-passe</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Definir Palavra-passe</button>
                </div>
            </form>
        </div>
    </div> 
</div>
{% endblock content%}

apps/users/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block content%}
    <div class="alert alert-info mt-4">
        Um e-mail foi enviado com as instruções para definir a sua Palavra-passe... Confirme, por favor.
    </div>
{% endblock content%}

apps/users/templates/users/password_reset_email.html
Recebeu este mail, depois de ter pedido para redefinir a sua senha...
Se é o que pretende, por favor, siga este link {{ protocol}}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}.
Se não pediu, por favor, ignore este mail.

O nome do user, no caso de ser ter esquecido é: {{ user.email }}

apps/users/templates/users/profile.html
{% extends "base_bg.html" %}
{% load crispy_forms_tags %}

{% block content%}
<div class="row">
    <div class="col-12 col-lg-8 offset-lg-2">
        <div class="heroimgbox-login p-4 my-5">
            <div class="media">
                <div class="media-body">
                    <h2 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h2>
                    <p class="text-secondary">{{ user.email }}</p>
                </div>
            </div>
            <form method="POST" enctype="multipart/form-data">
                <!-- 'enctype' to suport images in the form -->
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4" style="color: #e87e19;">Informação de Perfil</legend>
                        <div class="row">
                            <div class="col-12">
                                <div class="row">
                                    <div class="col-12 col-md-6">
                                        {{ u_form.email|as_crispy_field }}
                                    </div>
                                    <div class="col-12 col-md-6">
                                        {{ u_form.username|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12 col-md-6">
                                        {{ u_form.first_name|as_crispy_field }}
                                    </div>
                                    <div class="col-12 col-md-6">
                                        {{ u_form.last_name|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12 col-md-6 order-1">
                                        {{ u_form.bimby|as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                        </div>
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Atualizar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content%}

apps/users/templates/users/register.html
{% extends "base_bg.html" %}
{% load crispy_forms_tags %}

{% block content%}
<style>
    .x {
        color: #e87e19;;
    }
</style>
<div class="row">
    <div class="col-12 col-lg-8 offset-lg-2">
        <div class="heroimgbox-login p-4 my-5">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4" style="color: #e87e19;"><i style="width: 30px" class="fa-solid fa-user-plus"></i>Registo</legend>
                    <div class="row">
                        <div class="col-12">
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    {{ form.email|as_crispy_field }}
                                </div>
                                <div class="col-12 col-md-6">
                                    {{ form.username|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    {{ form.first_name|as_crispy_field }}
                                </div>
                                <div class="col-12 col-md-6">
                                    {{ form.last_name|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    {{ form.bimby|as_crispy_field }}
                                </div>
                                <div class="col-12 col-md-6">
                                    {{ form.loja|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    {{ form.aceito|as_crispy_field }}
                                    {{ form.role.as_hidden }}
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Registar</button>
                </div>
            </form>
            <div class="pb-2">
                <p class="text-muted">
                    Já se registou? <a href="{% url 'users:login' %}" style="color: #e87e19;">Inicie sessão aqui</a>
                </p>
            </div>
            <!-- <div class="border-top pt-3">
                <small class="text-muted">
                    Already Have An Account? <a class="ml-2" href="{% url 'users:login' %}">Sign In</a>
                </small>
            </div> -->
        </div>
    </div>
</div>
{% endblock content%}