apps/eventos/urls.py
from django.urls import path, reverse_lazy
from .views import detalhe_inscricao, home, receitas, promos,  evento, NovaInscricao

from apps.eventos.code_gen import CodeGeneration
from .views import BBCodeViewSet, detalhe_inscricao, evento, NovaInscricao, gen_storecodes, generate_bbcode, select_storecodes, import_store_codes, import_rewards, choice

app_name = "eventos"

urlpatterns = [
    path('', home, name='home'),
    path('receitas/', receitas, name='receitas'),
    path('promos/', promos, name='promos'),
    path('inscricao/', detalhe_inscricao, name='inscricao'),
    path('nova-inscricao/', NovaInscricao.as_view(), name='nova-inscricao'),
    path('evento/', evento, name='evento'),
    path('generate-codes/', gen_storecodes, name='gen_codes'),
    path('passatempo/', generate_bbcode, name='passatempo'),
    path('generate-list-codes/', select_storecodes, name='generate_list_code'),
    path('list-duplicate-store-codes/', CodeGeneration.list_duplicate_store_codes, name='list_duplicate_store_codes'),
    path('code/', BBCodeViewSet.as_view({'post': 'create'})),
    path('import-store-codes/', import_store_codes, name='import_store_codes'),
    path('import-rewards/', import_rewards, name='import_rewards'),
    path('choice/', choice, name='choice'),
    path('export_data/<str:choice>', CodeGeneration.export_data, name='export_data')
    
]

apps/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)
from .views import register, profile, login_register

app_name = "users"

urlpatterns = [
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('login_register/', login_register, name='login-register'),
    path(
        '',
        LoginView.as_view(
            template_name='users/login.html',
            redirect_authenticated_user=True
        ),
        name='login'
    ),
    path('logout/',
        LogoutView.as_view(template_name='users/logout.html'),
        name='logout'),
    path(
        'password-reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset.html',
            email_template_name='users/password_reset_email.html',
            success_url=reverse_lazy('users:password_reset_done')
        ),
        name='password_reset'
    ),
    path(
        'password-reset/done',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:login')
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    )
]

main/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.eventos.urls', namespace='eventos')),
    path('eventos/', include('apps.eventos.urls', namespace='apieventos')),
    path('locais/', include('apps.locais.urls', namespace='locais')),
    path('users/', include('apps.users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # media files

apps/eventos/models.py
from datetime import datetime
from django.db import models

from apps.locais.models import Local
from apps.users.models import User

# Create your models here.
class Evento(models.Model):
    nome = models.CharField(max_length=50)
    local = models.CharField(max_length=50)
    datahorainicio = models.DateTimeField()
    datahorafim = models.DateTimeField()
    #estado
    
    def __str__(self):
        return f'{self.nome} - {self.datahorainicio} a {self.datahorafim}'

class DetalhesEvento(models.Model):
    titulo = models.CharField(max_length=30)
    descricao = models.CharField(max_length=200)
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)

class SubEvento(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    local = models.ForeignKey(Local, on_delete=models.CASCADE)
    datahorainicio = models.DateTimeField()
    datahorafim = models.DateTimeField()
    notas = models.TextField(max_length=250, blank=True, null=True)

    def __str__(self):
        return f'{self.evento.nome} - {self.local}'

class Inscricao(models.Model):
    subevento = models.ForeignKey(SubEvento, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.subevento.evento} - {self.user}'

class StoreCode(models.Model):
    code = models.CharField(max_length=10, unique=True)
    is_redeemed = models.BooleanField(default=False)
    picked = models.BooleanField(default=False)
    event = models.ForeignKey(Evento, on_delete=models.CASCADE, blank=True, null=True, related_name='codes')

    def __str__(self):
        return f'{self.code} - {self.is_redeemed}'

class BBCode(models.Model):
    store_code = models.OneToOneField(StoreCode, on_delete=models.CASCADE, related_name='bbcode')
    code = models.CharField(max_length=7, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    valid = models.BooleanField(default=False)
    
    def __str__(self):
        return f'{self.code} - {self.store_code}'

class Reward(models.Model):
    reward = models.CharField(max_length=255, blank=True, null=True)
    bbcode = models.OneToOneField(BBCode, on_delete=models.CASCADE, blank=True, null=True, related_name='reward')
    event = models.ForeignKey(Evento, on_delete=models.CASCADE, blank=True, null=True, related_name='reward_event')
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    is_redeemed = models.BooleanField(default=False)
        
    def __str__(self):
        return f'{self.reward} - {self.bbcode} - {self.is_redeemed}'


class Message(models.Model):
    MsgId = models.CharField(max_length=255)
    From = models.CharField(max_length=255)
    To = models.CharField(max_length=255)
    Prefix = models.CharField(max_length=255)
    Msg = models.CharField(max_length=255)
    mcc = models.CharField(max_length=255)
    mnc = models.CharField(max_length=255)
    ReceivedDatetime = models.CharField(max_length=255)
    SegmentsTotalNumber = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.MsgId} - {self.Msg} - {self.ReceivedDatetime}'
    

apps/eventos/forms.py
from django import forms

from .models import Evento, Inscricao

from apps.eventos.models import Inscricao
from apps.users.models import User


class InscricaoForm(forms.ModelForm):
    class Meta:
        model = Inscricao
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.initial['user'] = user

class GenerateBBCodeForm(forms.Form):
    code = forms.CharField(label='', max_length=10)

class SelectCodesForm(forms.Form):
    num_codes = forms.IntegerField(min_value=1, max_value=10000)
    event = forms.ModelChoiceField(queryset=Evento.objects.all())

class StoreCodesForm(forms.Form):
    #num_codes = forms.IntegerField(min_value=1, max_value=100000)
    event = forms.ModelChoiceField(queryset=Evento.objects.all())
    excel_file = forms.FileField()

class RewardsForm(forms.Form):
    #num_codes = forms.IntegerField(min_value=1, max_value=100000)
    event = forms.ModelChoiceField(queryset=Evento.objects.all())
    excel_file = forms.FileField()

apps/eventos/views.py
import secrets
import string
import csv
import os
import time

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django.contrib import messages

from apps.eventos.code_gen import CodeGeneration
from apps.eventos.tasks import send_message
from main import settings
from .models import BBCode, Inscricao, Evento, Message, Reward, StoreCode
from .forms import GenerateBBCodeForm, InscricaoForm, RewardsForm, SelectCodesForm, StoreCodesForm
from django.urls import reverse_lazy, reverse

from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.parsers import JSONParser, FormParser, MultiPartParser
from .serializers import MessageSerializer
from rest_framework import status
from apps.users.roles import ADMIN, role_required
from django.contrib.auth.decorators import login_required
from django.core.files.storage import default_storage

def detalhe_inscricao(request):
    user = request.user
    i = Inscricao.objects.filter(user=user)
    if i:
        inscricao = i[0]
        separar = inscricao.subevento.local.coordenadas.split()
        coo1 = separar[0][0:15]
        coo2 = separar[1][0:15]
    else:
        i=" "
        separar=" "
        coo1 = " "
        coo2 = " "
    return render(request, 'eventos/inscricao.html', context={'user':user, 'inscricao':inscricao, 'coo1':coo1, 'coo2':coo2})

class NovaInscricao(CreateView):
    form_class = InscricaoForm
    model = Inscricao

    def get(self, request):
        self.user = request.user
        return super().get(request)

    def post(self, request):
        self.user = request.user
        return super().post(request)

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.user.id
        return kwargs

    # def get_context_data(self, **kwargs):
    #     ctx = super().get_context_data(**kwargs)
    #     # ctx['']
    #     return ctx

    def get_success_url(self):
        return reverse('eventos:evento')

def evento(request):
    evento = Evento.objects.last()
    # if request.user.is_authenticated:
    #     ins = Inscricao.objects.filter(user=request.user)
    #     if ins:
    #         return detalhe_inscricao(request)
    #     else:
    #         return render(request, 'eventos/evento.html', context={'evento':evento})
    ins = Inscricao.objects.filter(user=request.user)
    if ins:
        return detalhe_inscricao(request)
    else:
        return render(request, 'eventos/evento.html', context={'evento':evento})
    

def home(request):
    return render(request, 'eventos/home.html',
                    context={'title':'Dia Aberto Bimby®'})

def receitas(request):
    return render(request, 'eventos/receitas.html',
                    context={'title':'Receitas'})

def promos(request):
    return render(request, 'eventos/promos.html',
                    context={'title':'Promoções'})

class BBCodeViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]  # Set permission for this viewset to require authentication (Is set to Basic Auth)
    serializer_class = MessageSerializer  # Set the serializer class for the Message model
    parser_classes = [JSONParser, FormParser, MultiPartParser]

    def create(self, request, *args, **kwargs):
        data_dict = dict(request.data)  # Convert the QueryDict object to a dictionary
        for key in data_dict:
            data_dict[key] = str(data_dict[key][0])  # Convert all values to strings
        serializer = self.get_serializer(data=data_dict)  # Get the serializer for the incoming request data
        check_serializer = serializer.is_valid(raise_exception=False)  # Validate the incoming data
        for i in [element for element in data_dict]:
                kwargs[i] = data_dict[i]
        if not check_serializer:  # If validation fails, return a 400 response
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        else:
            serializer.save()
            #CodeGeneration.send_message(request,data_dict,**kwargs)
            task = send_message.delay(**kwargs)
            return HttpResponse(b'OK', content_type='text/plain', status=status.HTTP_200_OK)

@login_required
def generate_bbcode(request):
        check_bb = BBCode.objects.filter(user=request.user)
        sms_number = 4242
        REWARD_IMAGES = (
            ('Livro Itália', 'reward_image_1.jpg'),
            ('Livro Índia', 'reward_image_2.jpg'),
            ('Livro A Cozinhar se Conta uma História', 'reward_image_3.jpg'),
            ('Livro ao Sol e ao Pôr do Sol', 'reward_image_4.jpg'),
            ('Livro Chocolate', 'reward_image_5.jpg'),
            ('Livro Receitas Bimby S e XL', 'reward_image_6.jpg'),
        )

        if check_bb.exists() and Reward.objects.filter(bbcode=check_bb[0]).exists():
            reward = Reward.objects.get(bbcode=check_bb[0]).reward
            context = {
                'result': f'A sua recompensa',
                'reward_type': reward,
                'reward': True,
                'REWARD_IMAGES': REWARD_IMAGES
            }
            return render(request, 'eventos/generate_bbcode.html', context)
        elif check_bb.exists():
            context = {
                'result': True,
                'sms_number': sms_number,
                'bb_code_code': check_bb[0].code,
                'bb_code': True,
                'reward': False
            }
            return render(request, 'eventos/generate_bbcode.html', context)
        else:
            form = GenerateBBCodeForm(request.POST)
            if form.is_valid():
                code = form.cleaned_data['code']
                if check_bb.exists():
                    context = {
                        'result': f'Somente um BBCode por cliente... {check_bb[0].code}',
                    }
                    return render(request, 'eventos/generate_bbcode.html', context)
                else:
                    bb = CodeGeneration.generate_bb_code(request, code)
                    result = False
                    if bb:
                        result = True
                    else:
                        messages.error(request, 'Código já usado!')
                        return redirect(reverse('eventos:passatempo'))

                    context = {
                        'result': result,
                        'sms_number': sms_number,
                        'bb_code_code': bb,
                        'bb_code': True,
                        'reward': False
                    }
                    return render(request, 'eventos/generate_bbcode.html', context)
            else:
                form = GenerateBBCodeForm()
            context = {
                'form': form,
            }
            return render(request, 'eventos/generate_bbcode.html', context)

@login_required
@role_required(ADMIN)
def import_store_codes(request):
    from openpyxl import load_workbook
    
    if request.method == 'POST':
        form = StoreCodesForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.cleaned_data['event']
            excel_file = request.FILES['excel_file']

            # Load the Excel file and get the first sheet
            workbook = load_workbook(excel_file)
            sheet = workbook.active

            # Read the codes from the sheet
            codes = [str(cell.value).strip() for cell in sheet['A'] if cell.value and len(str(cell.value).strip()) <= 8]


            # Create StoreCode objects for the codes
            for code in codes:
                StoreCode.objects.create(code=code, event=event)

            # Redirect to the success page
            num_codes = StoreCode.objects.filter(event=event).count()
            return render(request, 'eventos/import_store_codes.html', {'num_codes': num_codes, 'form': form})
    else:
        form = StoreCodesForm()
    return render(request, 'eventos/import_store_codes.html', {'form': form})
 
@login_required
@role_required(ADMIN)
def import_rewards(request):
    from openpyxl import load_workbook
    
    if request.method == 'POST':
        form = RewardsForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.cleaned_data['event']
            excel_file = request.FILES['excel_file']

            # Load the Excel file and get the first sheet
            workbook = load_workbook(excel_file)
            sheet = workbook.active

            # Read the codes from the sheet
            rewards = [str(cell.value).strip() for cell in sheet['A'] if cell.value]

            # Create StoreCode objects for the codes
            for reward in rewards:
                Reward.objects.create(reward=reward, event=event)

            # Redirect to the success page
            num_codes = Reward.objects.all().count()
            return render(request, 'eventos/import_rewards.html', {'num_codes': num_codes, 'form': form})
    else:
        form = StoreCodesForm()
    return render(request, 'eventos/import_rewards.html', {'form': form})


### NOT USED ###

@login_required
@role_required(ADMIN)
def gen_storecodes(request):
    if request.method == 'POST':
        form = StoreCodesForm(request.POST)
        if form.is_valid():
            num_codes = form.cleaned_data['num_codes']
            eventid = form.cleaned_data['event']
            storecodes = CodeGeneration.generate_store_codes(request, num_codes, eventid.id)
            evento = Evento.objects.get(id=eventid.id)
            codes = evento.codes.all()
            unused_codes = codes.filter(is_redeemed=False, picked=False).count()

apps/eventos/templates/eventos/evento.html
{% extends "base.html" %}

{% block content%}
    <div class="content-section">
        <b>Nome:</b> {{ evento.nome }}
        <br>
        <b>Data:</b> {{ evento.datahorainicio|date:"d/m/Y"}}
        <br>
        <b>Hora:</b> {{ evento.datahorainicio|date:"h:i" }}
        <br><br>
        <a class="btn" href="{% url 'eventos:nova-inscricao' %}">Inscrever</a>
        
        
    </div>

{% endblock content%}

apps/eventos/templates/eventos/generate_bbcode.html
{% extends 'base_bg.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="row">
	<div class="col-12 col-md-8 offset-md-2">
		<div class="heroimgbox-login p-4 my-5">
			
			{% if not user.is_authenticated %}
				<h5 class="text-center">Ainda não se registou?</h5>
				<div class="text-center mb-4">
					<a class="btn" href="{% url 'users:register' %}">Registar</a>
				</div>
				<h5 class="text-center">Já está registado?</h5>
				<div class="text-center">
					<a class="btn" href="{% url 'users:login' %}">Login</a> <br>
				</div>
			{% else %}
			
				{% if not reward and not bb_code %}
					<legend class="border-bottom mb-4" style="color: #e87e19;">Insira o código que lhe foi dado na Loja</legend>
					<div class="mb-3">
						<form method="post">
						{% csrf_token %}
						{{ form|crispy }}
							<button class="btn mt-3" type="submit">GERAR</button>
						</form>
					</div>
				{% endif %}

				{% if result %}
					<div class="reward">
            			{% if not reward %}
                    <legend class="mb-2" style="color: #e87e19;">Envie um SMS* para o {{ sms_number }} com o código {{ bb_code_code }}</legend>
					<span style="font-size: 0.75rem;">* O custo por SMS enviado para o nº 4242 é de aproximadamente 0,10€, de acordo com as condições de tarifário e operador para números curtos.</span>
            			{% endif %}
					{% for i, image_filename in REWARD_IMAGES %}
						{% if reward_type == i %}
                			<legend class="mb-4" style="color: #e87e19;">{{ result }}</legend>
								<div class="d-flex">
									<img src="{% static 'images/'|add:image_filename %}" alt="{{ reward }}" class="mx-auto">
								</div>
								<h5 style="color: #e87e19;">{{ reward_type }}</h5>
								<h6>Parabéns! Pode fazer o levantamento do seu prémio a partir de dia 21 de março de 2023 na Loja onde participou no evento e no passatempo.*</h6>
								<span style="font-size: 0.75rem;">*Se está a participar na Loja de Coimbra, Loja de Aveiro ou Vorwerk Studios de Portimão ou Viana do Castelo, entraremos em contacto consigo via email para comunicar onde será feito o levantamento do seu prémio.</span>
							{% endif %}
						{% endfor %}
					</div>
        		{% elif not result and bb_code%}
        			<div class="reward">
          				{% if not reward %}
            				<legend class="mb-4" style="color: #e87e19;">Código inválido</legend>
          				{% endif %}
					</div>
				{% endif %}
			
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

apps/eventos/templates/eventos/generete_storecodes.html
{% extends 'base.html' %}

{% block content %}
  <h1>Códigos para lojas</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="SUBMIT">
  </form>
  {% if storecodes %}
    <p>{{ storecodes }} Códigos gerados com sucesso... </p>
    <p> Total de códigos {{ unused_codes }} disponiveis... </p>
  {% endif %}
{% endblock %}

apps/eventos/templates/eventos/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content%}
<div class="">
    <div class="row pb-5" style="margin-left: -16px; margin-right: -16px;">
        <div class="col-12 px-0">
            <img src="{% static 'images/modulo-1.jpg' %}" alt="" width="100%">
        </div>
        <div class="col-12 col-lg-8 offset-lg-2 align-self-center">
            <div id="aretodos" class="heroimg pb-2 pt-4 px-4">
                <h2 style="font-family: Merriweather;" class="text-center pb-3"><b> Já ouviu dizer que o <span style="color: #e87e19;">ar</span> é de todos?</b></h2>
                <h6 style="font-family: Source-Regular;" class="pb-3">
                    O dia aberto Bimby® vai ser uma lufada de <span style="color: #e87e19;">ar</span> fresco para a sua cozinha.<br>
                    Vamos dar-lhe <span style="color: #e87e19;">AR</span> para poup<span style="color: #e87e19;">AR</span>, <span style="color: #e87e19;">AR</span> para organiz<span style="color: #e87e19;">AR</span>, <span style="color: #e87e19;">AR</span> para plane<span style="color: #e87e19;">AR</span>, <span style="color: #e87e19;">AR</span> para retom<span style="color: #e87e19;">AR</span> e o <span style="color: #e87e19;">AR</span> para respir<span style="color: #e87e19;">AR</span>.
                </h6>
                <h6 style="font-family: Source-Regular;" class="pb-1 mb-0">Venha conhecer o novo acessório, a Mandolina Bimby® e aproveitar oportunidades incríveis para rentabilizar a sua Bimby®.
                Visite-nos no dia 11 de março de 2023 das 10h às 20h.</h6> <br>
            </div>
        </div>
    </div>
    <div class="row pb-5">
        <div class="col-12 col-lg-8 embed-responsive embed-responsive-16by9 mx-auto">
            <iframe class="embed-responsive-item m-auto p-md-2" src="https://www.youtube.com/embed/c4MCULXC1oE" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6 col-xl-3 d-flex mb-4 align-items-stretch">
            <div class="m-1 heroimgbox">
                <img src="{% static 'images/modulo-3.png' %}" alt="" width="100%" class="heroimg">
                <div class="text-center p-3 mt-2">
                    <h4 class="text-center">Conhecer a Mandolina</h4>
                    Fatie e rale ingredientes diferentes, de forma a dar sabor e textura a uma grande variedade de pratos.
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-xl-3 d-flex mb-4 align-items-stretch">
            <div class="m-1 heroimgbox">
                <img src="{% static 'images/modulo-4.png' %}" alt="" width="100%" class="heroimg">
                <div class="text-center p-3 mt-2">
                    <h4 class="text-center">Conhecer a Bimby®</h4>
                    Cozinhar com a Bimby® significa partilhar refeições deliciosas com quem mais gosta. Preparado para ver a Bimby® ao vivo?
                </div>             
            </div>
        </div>
        <div class="col-12 col-md-6 col-xl-3 d-flex mb-4 align-items-stretch">
            <div class="m-1 heroimgbox" style="display: grid;">
                <img src="{% static 'images/modulo-5.png' %}" alt="" width="82%" class="heroimg m-auto">
                <div class="text-center p-3 mt-1">
                    <h4 class="text-center">Campanha de Retoma</h4>
                        Se tem uma Bimby® TM21, TM31, TM5 ou qualquer outro robot de cozinha multifunções que cozinhe, vai adorar esta oportunidade.
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-xl-3 d-flex mb-4 align-items-stretch">
            <div class="m-1 heroimgbox">
                <img src="{% static 'images/modulo-6.png' %}" alt="" width="100%" class="heroimg">
                <div class="text-center p-3 mt-2">
                    <h4 class="text-center">Promoções</h4>
                        É hora de poupar! Descontos até 60%.*<br>
                        <span style="font-size: 0.75rem;">* descontos apenas nas lojas físicas onde o evento se realiza durante o dia 11 de março</span>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-6 col-xl-6 mb-4 align-items-stretch">
            <div class="m-1 heroimgbox" style="background-color: rgba(4, 109, 132, 0.1);">
                <div class="p-3 mt-2">
                    <h4 class="text-center">Passatempo</h4>
                    <h6 class="text-center">Participe no passatempo e habilite-se a ganhar prémios incríveis. Existem prémios para todos os gostos!</h6>
                    <div class="my-2 text-center">
                        <a class="btn btn-outline-info" href="{% url 'eventos:choice' %}">Participar</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-xl-6 mb-4 align-items-stretch">
            <div class="m-1 heroimgbox">
                <div class="p-3 mt-2">
                    <h4 class="text-center">Receitas</h4>
                    <h6 class="text-center">Sugestões de receitas que farão a sua despensa mais rica e receitas para explorar o novo acessório Bimby® - Mandolina.</h6>
                    <div class="my-2 text-center">
                        <a class="btn btn-outline-info" href="{% url 'eventos:receitas' %}">Saber Mais</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content%}

apps/eventos/templates/eventos/import_rewards.html
{% extends 'base.html' %}

{% block content %}
  <h1>Import Rewards</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Import</button>
  </form>
  {% if num_codes %}
    <p>{{ num_codes }} Prémios importados com sucesso... </p>
  {% endif %}
{% endblock %}

apps/eventos/templates/eventos/import_store_codes.html
{% extends 'base.html' %}

{% block content %}
  <h1>Import Store Codes</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Import</button>
  </form>
  {% if num_codes %}
    <p>{{ num_codes }} Códigos importados com sucesso... </p>
  {% endif %}
{% endblock %}

apps/eventos/templates/eventos/inscricao.html
{% extends "base.html" %}

{% block content %}
    <div class="content-section">
        <b>Evento:</b> {{ inscricao.subevento.evento.nome }}
        <br>
        <b>Data: </b>{{ inscricao.subevento.datahorainicio|date:"d/m/Y" }}
        <br>
        <b>Hora: </b>{{ inscricao.subevento.datahorainicio|date:"h:i" }}
        <br>
        <b>Local: </b>{{ inscricao.subevento.local }}
        <br>
        <b>Morada: </b>{{ inscricao.subevento.local.enderecoum }}
        {% if inscricao.subevento.local.enderecodois %}
        , {{ inscricao.subevento.local.enderecodois }}
        {% endif %}
        <br>
        <b>Código Postal: </b>{{ inscricao.subevento.local.codigopostal }}
        <br>
        <br>
        <a class="btn" href="https://www.waze.com/ul?ll={{coo1}}00%2C{{coo2}}00&navigate=yes&zoom=17" target="_blank"><b>Waze</b></a>
        <a class="btn" href="https://www.google.com/maps/search/?api=1&query={{coo1}}%2C{{coo2}}" target="_blank"><b>Google Maps</b></a>
        
    </div>

{% endblock content %}

apps/eventos/templates/eventos/inscricao_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content%}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <div class="row form-group">
                    <div class="col-md-6">
                        {{ form.subevento|as_crispy_field }}
                    </div>
                        {{ form.user|as_crispy_field }}
                </div>
            </fieldset>
            <div class="form-group">
                <button class="btn" type="submit">Guardar</button>
                <a class="btn btn-outline-danger" style="border-color: red;" href="{% url 'eventos:inscricao' %}">Cancelar</a>
            </div>
        </form>
    </div>
{% endblock content%}

apps/eventos/templates/eventos/select_codes.html
{% extends 'base.html' %}

{% block content %}
  <h1>Selecionar Códigos</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="SUBMIT">
  </form>

  {% if selected_codes %}
    <a href="{{ MEDIA_URL }}{{ filename }}" download>Download</a>
  {% endif %}
{% endblock %}